default: driver-map.cpp unit-map.cpp map.cpp
	g++ map-demo.cpp unit-map.cpp map.cpp -std=c++11 -o demo.o

test: driver-map.cpp unit-map.cpp map.cpp
	g++ driver-map.cpp unit-map.cpp map.cpp -std=c++11 -o unit-map.o
