default:
	g++ card.cpp continent.cpp deck-demo.cpp deck.cpp territory.cpp unit-deck.cpp -std=c++11 -o deck.o

test:
	g++ card.cpp continent.cpp driver-deck.cpp deck.cpp territory.cpp unit-deck.cpp -std=c++11 -o test.o
